version: '3'
volumes:
  redis:
  postgres:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/DockerFile
    depends_on:
      - db
      - redis
  db:
    image: 'postgres:11-alpine'
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env'
    ports:
      - '5432:5432'
  redis:
    image: 'redis:4-alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - 'redis:/data'
      - './docker/redis/redis.conf:/usr/local/etc/redis/redis.conf'
    ports:
      - '6379:6379'
  web:
    build:
      context: .
      dockerfile: ./docker/web/DockerFile
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443

  sidekiq:
    depends_on:
      - db
      - redis
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/app'
    env_file:
      - '.env'
