# vim:set ft=dockerfile:
FROM postgres:11-alpine
ENV PGPASSWORD password

ENV POSTGRES_PASSWORD=password
ENV POSTGRES_USER=postgres
# ENV POSTGRES_DB=db
# RUN chmod 777 /var/lib/postgresql/data
# COPY *.sql /tmp/psql_data/
# RUN chmod 777 /tmp/psql_data/structure.sql
# COPY init_docker_postgres.sh /docker-entrypoint-initdb.d/
# COPY structure.sql /docker-entrypoint-initdb.d/
# EXPOSE 5432
# CMD ["postgres"]

