version: '3'

services:
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
      - '/home/deploy/pgdata/etc:/etc/postgresql'
      - '/home/deploy/pgdata/log:/var/log/postgresql'
      - '/home/deploy/pgdata/data:/var/lib/postgresql/data'
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass wsciAqNwgG9D7cF^gVXi9NivbUXGzZ1qDia4bQ
    volumes:
      - 'redis:/data'

  sidekiq:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile-sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/movierecommendationswithml'
      - 'bundle_cache:/bundle'
    links:
      - 'db'
      - 'redis'
    env_file:
      - '.env'
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - '.:/movierecommendationswithml'
      - 'bundle_cache:/bundle'
      # Map bundle cache to named volume
    depends_on:
      - 'db'
      - 'sidekiq'
    links:
      - 'db:db'
    env_file:
      - '.env'

        #bundle_cache:
        #image: busybox
        #volumes:
        # - /bundle_cache
 
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
        - '/home/deploy/nginx/log:/var/log'
    depends_on:
      - 'app'
    ports:
      - '80:80'
      - '443:443'

volumes:
  bundle_cache:
  redis:
  postgres-data:
    driver: local
