version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server --requirepass yourpassword
    volumes:
      - 'redis:/data'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/app'
    env_file:
      - '.env'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - 'db'
      - 'sidekiq'
    links:
      - 'db'
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - 'app'
    ports:
      - '80:80'
      - '443:443'

volumes:
  redis:
  postgres:
