default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: db

development:
  <<: *default
  database: movierecommendationswithml_development

production:
  <<: *default
  database: movierecommendationswithml_production

