default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: movierecommendationswithml_development
  host: localhost

production:
  <<: *default
  database: movierecommendationswithml_production
  username: postgres
  password: password
  host: db
